# Generated by Django 4.2.4 on 2023-09-05 13:19

import digital.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalstorage',
            name='storage_size',
        ),
        migrations.AddField(
            model_name='digitalstorage',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=digital.models.user_upload_path, validators=[digital.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='digitalstorage',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to=digital.models.user_upload_path, validators=[digital.models.validate_music_file_extension]),
        ),
        migrations.AddField(
            model_name='digitalstorage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=digital.models.user_upload_path, validators=[digital.models.validate_video_extension]),
        ),
        migrations.AlterField(
            model_name='digitalstorage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
