# Generated by Django 4.2.4 on 2023-09-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_remove_digitalstorage_storage_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalstorage',
            old_name='image',
            new_name='image_file',
        ),
    ]
